// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore.Design;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CalPEATS.EfCore.Sandbox
{
    public class UserDbContextFactory : IDesignTimeDbContextFactory<UserDbContext>
    {
        public UserDbContext CreateDbContext(string[] args)
        {
            return new UserDbContext();
        }
    }
}
// </auto-generated>
