// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace CalPEATS.EfCore.Sandbox
{
    // user_login
    public class UserLogin
    {
        [Required]
        [Display(Name = "Id")]
        public long Id { get; set; } // Id

        [Required]
        [Display(Name = "User type ID")]
        public long UserTypeId { get; set; } // UserTypeId

        [Key, Column(Order = 2)]
        [Required(AllowEmptyStrings = true)]
        [Display(Name = "User name")]
        public string UserName { get; set; } // UserName (Primary key)

        [Required]
        [Display(Name = "Password hash")]
        public byte[] PasswordHash { get; set; } // PasswordHash

        [Required]
        [Display(Name = "Last time server validated")]
        public DateTime LastTimeServerValidated { get; set; } // LastTimeServerValidated

        [Required]
        [Display(Name = "Salt")]
        public byte[] Salt { get; set; } // Salt

        [Display(Name = "Can do inovcd")]
        public string CanDoInovcd { get; set; } // CanDoINOVCD

        [Display(Name = "Counties")]
        public string Counties { get; set; } // Counties
    }

}
// </auto-generated>
