// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading;
using System.Threading.Tasks;

namespace CalPEATS.EfCore.Sandbox
{
    // _version
    public class Version
    {
        [Key, Column(Order = 0)]
        [Required(AllowEmptyStrings = true)]
        [Display(Name = "Schema")]
        public string Schema { get; set; } // schema (Primary key)

        [Display(Name = "Build")]
        public string Build { get; set; } // build

        [Display(Name = "Created date")]
        public DateTime? CreatedDate { get; set; } // created_date
    }

}
// </auto-generated>
