// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CalPEATS.EfCore.Sandbox
{
    // user_login
    public class UserLoginConfiguration : IEntityTypeConfiguration<UserLogin>
    {
        public void Configure(EntityTypeBuilder<UserLogin> builder)
        {
            builder.ToTable("user_login", "main");
            builder.HasKey(x => x.UserName);

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("integer").IsRequired();
            builder.Property(x => x.UserTypeId).HasColumnName(@"UserTypeId").HasColumnType("integer").IsRequired();
            builder.Property(x => x.UserName).HasColumnName(@"UserName").HasColumnType("varchar").IsRequired().IsUnicode(false).ValueGeneratedOnAdd();
            builder.Property(x => x.PasswordHash).HasColumnName(@"PasswordHash").HasColumnType("blob").IsRequired();
            builder.Property(x => x.LastTimeServerValidated).HasColumnName(@"LastTimeServerValidated").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.Salt).HasColumnName(@"Salt").HasColumnType("blob").IsRequired();
            builder.Property(x => x.CanDoInovcd).HasColumnName(@"CanDoINOVCD").HasColumnType("varchar").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.Counties).HasColumnName(@"Counties").HasColumnType("varchar").IsRequired(false).IsUnicode(false);
        }
    }

}
// </auto-generated>
