// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CalPEATS.EfCore.Sandbox
{
    // _version
    public class VersionConfiguration : IEntityTypeConfiguration<Version>
    {
        public void Configure(EntityTypeBuilder<Version> builder)
        {
            builder.ToTable("_version", "main");
            builder.HasKey(x => x.Schema);

            builder.Property(x => x.Schema).HasColumnName(@"schema").HasColumnType("varchar").IsRequired().IsUnicode(false).ValueGeneratedOnAdd();
            builder.Property(x => x.Build).HasColumnName(@"build").HasColumnType("varchar").IsRequired(false).IsUnicode(false);
            builder.Property(x => x.CreatedDate).HasColumnName(@"created_date").HasColumnType("datetime").IsRequired(false);
        }
    }

}
// </auto-generated>
